# Generated by Django 5.0.6 on 2025-03-09 21:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('creada_en', models.DateField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dentist_appointments', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shared.citaestadosmodel')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dentista', 'hora'), ('paciente', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='DienteSeccionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('diente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.dientemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField(default=datetime.datetime(2025, 4, 8, 21, 55, 12, 840790, tzinfo=datetime.timezone.utc))),
                ('total_pagar', models.FloatField()),
                ('activa', models.BooleanField(default=False)),
                ('iva', models.FloatField(default=19.0)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.citamodel')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.facturamodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateField(auto_now_add=True)),
                ('diente_condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.dienteestadosmodel')),
                ('diente_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.dienteseccionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OdontogramaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dientemodel',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.odontogramamodel'),
        ),
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.FloatField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('estado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.pagoestadosmodel')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.facturamodel')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.pagometodosmodel')),
            ],
        ),
    ]
