# Generated by Django 5.0.6 on 2025-03-22 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='fecha_limite',
            field=models.DateField(default=datetime.datetime(2025, 4, 21, 11, 47, 10, 730179, tzinfo=datetime.timezone.utc)),
        ),
    ]
