# Generated by Django 5.0.6 on 2025-03-22 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_facturamodel_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='fecha_limite',
            field=models.DateField(default=datetime.datetime(2025, 4, 21, 11, 49, 13, 356885, tzinfo=datetime.timezone.utc)),
        ),
    ]
