# Generated by Django 5.0.6 on 2024-09-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_odontologydomain_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologydomain',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='shared.odontology'),
        ),
    ]
