# Generated by Django 5.0.6 on 2024-06-23 21:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dentist_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary_appointments', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shared.appointmentstatus')),
            ],
            options={
                'unique_together': {('dentist', 'date'), ('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.datetime(2024, 7, 23, 21, 53, 36, 249485, tzinfo=datetime.timezone.utc))),
                ('total_to_pay', models.FloatField()),
                ('is_done', models.BooleanField(default=False)),
                ('iva_rate', models.FloatField(default=19.0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.bill')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.paymentmethod')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.paymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.odontogram')),
            ],
        ),
        migrations.CreateModel(
            name='ToothSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.tooth')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tooth_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.toothcondition')),
                ('tooth_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.toothsection')),
            ],
        ),
    ]
