# Generated by Django 5.0.6 on 2024-06-23 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 21, 53, 42, 249630, tzinfo=datetime.timezone.utc)),
        ),
    ]
