# Generated by Django 5.0.6 on 2024-07-19 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 8, 18, 2, 59, 47, 458760, tzinfo=datetime.timezone.utc)),
        ),
    ]
