# Generated by Django 5.0.6 on 2024-08-20 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 12, 18, 15, 115380, tzinfo=datetime.timezone.utc)),
        ),
    ]
