# Generated by Django 5.0.6 on 2024-09-02 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 10, 2, 2, 35, 38, 114025, tzinfo=datetime.timezone.utc)),
        ),
    ]
