# Generated by Django 5.0.6 on 2024-09-02 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 10, 2, 2, 36, 11, 910457, tzinfo=datetime.timezone.utc)),
        ),
    ]
