# Generated by Django 5.0.6 on 2024-09-08 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 10, 8, 23, 46, 56, 400751, tzinfo=datetime.timezone.utc)),
        ),
    ]
