# Generated by Django 5.0.6 on 2024-10-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_bill_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 16, 29, 36, 466638, tzinfo=datetime.timezone.utc)),
        ),
    ]
